(* Support code shared by the tests of the ppx.

   A test is an executable called with the name of an output file as its only
   argument. The output is compared with the expected one by dune and promoted
   (in the source tree, ignored by git) even if the test fails, so that the
   code generated by the ppx can always be inspected:

   - the Elpi declarations of the data types derived by the ppx come first
     (the builtins are declared in the output file, see BuiltIn.declare ~file_name)
   - then, if the test runs a program, the program itself
   - then warnings, errors and the output of the program, as comments

   An exception is not a failure of the executable: it is recorded in the
   output, and the test fails because the output differs from the expected one.
*)

open Elpi.API

let output_file = Sys.argv.(1)

let append s =
  let oc = open_out_gen [Open_wronly; Open_append; Open_creat] 0o644 output_file in
  output_string oc s;
  close_out oc

let record_exception = function
  | Compile.CompileError(loc, msg) ->
      append (Printf.sprintf "\n/* COMPILE ERROR: %s\n   at: %s */\n" msg
        (match loc with None -> "unknown location" | Some l -> Ast.Loc.show l))
  | e -> append (Printf.sprintf "\n/* EXCEPTION: %s */\n" (Printexc.to_string e))

(* Run [f], never fails: exceptions end up in the output file *)
let protect f =
  (try f () with e -> record_exception e);
  exit 0

(* Output file as a formatter, used for the output of the program, the errors
   and the warnings. Warnings (eg type checking ones) are part of the output. *)
let formatter_on_output () =
  let out = open_out_gen [Open_wronly; Open_append] 0o644 output_file in
  let fmt = Format.formatter_of_out_channel out in
  Setup.set_err_formatter fmt;
  Setup.set_std_formatter fmt;
  Setup.set_warn (fun ?loc ~id:_ msg ->
    Format.fprintf fmt "@\n/* WARNING: %s@\n   at: %s */@\n" msg
      (match loc with None -> "unknown location" | Some l -> Ast.Loc.show l));
  fmt, (fun () -> Format.pp_print_flush fmt (); close_out out)

(* Document [builtin] in the output first, so that the output is available
   even if type checking it (in Setup.init) fails *)
let document builtin = BuiltIn.document_file builtin

let init builtin =
  Setup.init ~builtins:[Elpi.Builtin.std_builtins; builtin] ()

(* Test that the declarations in [builtin] type check *)
let check_declarations builtin =
  protect (fun () ->
    document builtin;
    let _, close = formatter_on_output () in
    ignore (init builtin);
    close ())

(* Test that [program] runs the query [main.] successfully, using [builtin]. The
   program is copied in the output, followed by what it prints. *)
let run_program builtin program =
  protect (fun () ->
    document builtin;
    append ("\n" ^ program);
    let fmt, close = formatter_on_output () in
    let elpi = init builtin in
    let ast = Parse.program_from ~elpi ~loc:(Ast.Loc.initial "test")
        ~digest:(Digest.string program) (Lexing.from_string program) in
    let goal = Parse.goal ~elpi ~loc:(Ast.Loc.initial "test") ~text:"main." in
    let program = Compile.program ~elpi ~flags:Compile.default_flags ast in
    let goal = Compile.query program goal in
    let exe = Compile.optimize goal in
    (* what the program prints is a comment *)
    Format.fprintf fmt "@\n/* OUTPUT@\n";
    let finish () = Format.fprintf fmt "*/@\n"; close () in
    match Execute.once exe with
    | Execute.Success _ -> finish ()
    | _ -> finish (); failwith "the goal main did not succeed"
    | exception e -> finish (); raise e)
