opam-version: "2.0"
maintainer: "Enrico Tassi <enrico.tassi@inria.fr>"
authors: [ "Claudio Sacerdoti Coen" "Enrico Tassi" ]
license: "LGPL-2.1-or-later"
homepage: "https://github.com/LPCIC/elpi"
doc: "https://LPCIC.github.io/elpi/"
dev-repo: "git+https://github.com/LPCIC/elpi.git"
bug-reports: "https://github.com/LPCIC/elpi/issues"

build: [
  ["dune" "subst"] {dev}
  ["dune" "build" "-p" name "-j" jobs]
]
x-maintenance-intent: ["(latest)"]
depends: [
  "ocaml" {>= "4.13.0" }
  "dune" {>= "2.9.0"}
  "elpi" {= version}
  "ppxlib" {>= "0.12.0"}
  "re" {>= "1.7.2"}
  "ppx_deriving" {with-test & >= "4.3"}
]
synopsis: "PPX deriver to interface OCaml data types with ELPI"
description: """
ppx_elpi synthesizes the glue code needed to exchange OCaml data types with
the ELPI interpreter. Use [@@deriving elpi] on a type declaration."""
