#!/bin/bash
set -x
set -e
ulimit -s 16384
export RUNNER=elpi
export PATH=${TOP}:$PATH
export VARIANT=${VARIANT}
if which timeout >/dev/null 2>&1; then TIMEOUT=timeout; else TIMEOUT=gtimeout; fi
if which gtime >/dev/null 2>&1; then TIME=gtime; else TIME=/usr/bin/time; fi
FILE=`(readlink -f $1 || realpath $1) 2>/dev/null`
if [ -e ${FILE%%.elpi}.stdin ]; then
	cat ${FILE%%.elpi}.stdin | \
	$TIMEOUT $MAX_TIME $TIME  --format='%x %E %U %Mk' -o $2 \
		${TOP}/elpi${VARIANT} -no-tc $1
else
    if [ -e "$FILE/Makefile" ]; then
	cd $FILE
	make
	$TIMEOUT $MAX_TIME $TIME  --format='%x %E %U %Mk' -o $2 \
		make run
    else
	$TIMEOUT $MAX_TIME $TIME  --format='%x %E %U %Mk' -o $2 \
		${TOP}/elpi${VARIANT} -no-tc -test $1
    fi
fi
