#!/bin/sh
set -x
set -e
NAME=`basename $1`
BASE=${TOP}/../teyjus/source

ulimit -s 32768
export RUNNER=teyjus
export PATH=${BASE}:$PATH

if which tjsim 2>/dev/null; then
  :
else
  echo 2 0 0 0k > $2
  exit 1
fi

cd $1
if [ -e "Makefile" ]; then
	make
	timeout $MAX_TIME /usr/bin/time --quiet --format='%x %E %U %Mk' -o $2 \
		make run
else
	${BASE}/tjcc $NAME -o $NAME.lpo
	${BASE}/tjlink $NAME
	timeout $MAX_TIME /usr/bin/time --quiet --format='%x %E %U %Mk' -o $2 \
		${BASE}/tjsim -m 1 -b -s 'main.' $NAME
fi

