%right BIND
%nonassoc QDASH VDASH
%right OR
%right DDARROW
%right DDARROWBANG
%right CONJ CONJ2
%right ARROW
%right DARROW
%nonassoc EQ EQ2 FAMILY_GT FAMILY_LT IS
%right CONS
%nonassoc FAMILY_TICK
%left FAMILY_EXP FAMILY_PLUS MINUS MINUSi MINUSr MINUSs
%left DIV FAMILY_TIMES MOD SLASH
%right FAMILY_MINUS
%nonassoc FAMILY_BTICK
%right FAMILY_EQ
%right FAMILY_OR
%right FAMILY_AND
%left FAMILY_SHARP
%nonassoc FAMILY_TILDE
%nonassoc FAMILY_QMARK
%%
