PACKAGE = ng_disambiguation
PREDICATES =

INTERFACE_FILES =		\
	nnumber_notation.mli    \
	disambiguateChoices.mli \
  nCicDisambiguate.mli    \
	grafiteDisambiguate.mli \
	$(NULL)
IMPLEMENTATION_FILES =		\
  $(INTERFACE_FILES:%.mli=%.ml)


include ../../Makefile.defs
include ../Makefile.common
