PACKAGE = ng_cic_content

INTERFACE_FILES = \
	ncic2astMatcher.mli \
	interpretations.mli

IMPLEMENTATION_FILES = $(INTERFACE_FILES:%.mli=%.ml)


all:


include ../../Makefile.defs
include ../Makefile.common
