PACKAGE = ng_tactics

INTERFACE_FILES = \
  continuationals.mli \
	nCicTacReduction.mli \
	nTacStatus.mli \
	nCicElim.mli \
	nTactics.mli \
        nnAuto.mli \
	nDestructTac.mli \
	nInversion.mli

IMPLEMENTATION_FILES = $(INTERFACE_FILES:%.mli=%.ml)


all:


include ../../Makefile.defs
include ../Makefile.common
