name: Doc workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build doc

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install sphinx
        run: |
          pip3 install Sphinx sphinx-rtd-theme in-place

      - name: Install ocaml
        uses: avsm/setup-ocaml@v2
        with:
          ocaml-compiler: 4.13.x
          opam-local-packages:

      - name: Build
        run: |
          eval $(opam env)
          opam install ./elpi.opam --deps-only --with-doc
          make doc-build

      - name: Save doc artifact
        uses: actions/upload-artifact@v3
        with:
          name: doc
          path: docs/build

      - name: deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          branch: gh-pages
          folder: docs/build/html
